### ISSUE TITLE
Simplify and Standardize all Script / Code execution

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#93]
Spiffworkflow provides a nearly good method for executing code consistently that is respected throughout the cr-connect-workflow.  It provides a place 

- [ ]  Set this up as an API endpoint, where you could send the function and current task data in, and get a response back with the result.  Then everything  behaves the same by definition.  
- [ ]  Assure that all variables used in the task.data are camel case to avoid potential name space collisions.
- [ ]  Script tasks should execute as functions - and not require the #! before them. 
- [ ]
